spring:

  kafka:
    topics:
      pm25: test



    bootstrap-servers: 172.17.0.1:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer






